### ISSUE TITLE
What does this script do again

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Linux-Mint-to-feren-OS#1]
I just want to know what this actually does. Whats it supposed to do i'm little lost

T.J Wolf here

**Comment by feren** [comment]
Turn Linux Mint into feren OS (without uninstalling that much)

**Comment by feren** [comment]
BTW, the archive is temporarily deleted because it didn't seem to work...

**Comment by tjw0lf** [comment]
Did you update it again""" BTW: Removed the user-bricking command﻿ where's this new script

**Comment by feren** [comment]
@tjw0lf I'm trying to compress it now into an uploadable ZIP

**Comment by tjw0lf** [comment]
Ok post link here when done i'll try it again happy to help as much as i can. I did it wrong anyway the first time anyway but those errors are still there from sudo video but will try it again right i forgot to  use sudo bash like showed lol. thats why i didn't get logon manger probably

**Comment by tjw0lf** [comment]
Also when done should i install in su root sudo bash "./Convert to feren OS.sh"

or normal  sudo bash "./Convert to feren OS.sh"

**Comment by feren** [comment]
New link: https://drive.google.com/open?id=0B6gF35ZZCULwcHNBUU5qRDhNa00
Dunno, I'd say just `sudo bash` on its own will do.

**Comment by tjw0lf** [comment]
OK will try again let you know give me a minute or so have to install Mint Cin* again

**Comment by feren** [comment]
You may not have to reinstall it, try TTY1, then these commands:
```
sudo chown -hR test:test /home/test/.ICEauthority
sudo chmod 644 /home/test/.dmrc
sudo chmod 755 /home/test/.ICEauthority
sudo chown -hR test:test /home/test/.dmrc﻿
```

**Comment by feren** [comment]
**(test = Your Username)** (GitHub doesn't auto-update)

**Comment by tjw0lf** [comment]
its already reinstalled no worry's. I will try that for next time if this doesn't work for future

**Comment by feren** [comment]
BTW, in case you're curious:
Changes in this version:
- Might've fixed the User Bricking
- Boot Screen Change
- Mint Welcome and other Mint Tools patched into feren OS mods
- A warning tag on the GitHub main page

**Comment by tjw0lf** [comment]
its hung up on the script. still waiting
here's the whole thing txt file
https://drive.google.com/open?id=0B-Ps2sVu6Le8cUpRemE3aW9KdzQ

**Comment by tjw0lf** [comment]
should i try it again in su root or just close and restart see what happens

**Comment by tjw0lf** [comment]
https://www.youtube.com/watch?v=fvQQrnbPyKw

**Comment by feren** [comment]
@tjw0lf The text file says the script finished.

**Comment by feren** [comment]
BTW, I'm updating it to add support for fonts & a working user defaults script

**Comment by feren** [comment]
Welp, it's going...
![screenshot from 2016-11-13 13-39-02](https://cloud.githubusercontent.com/assets/11057934/20246053/8e4e6a94-a9a6-11e6-84ec-2175caa12195.png)

**Comment by feren** [comment]
@tjw0lf UNLEASHING THE NEWEST SCRIPT: The script may finally be ready! :)
New changes:

- Fixes to Plymouth theme installation
- Fonts
- User Defaults are now in another script to work user-level
- Icons are now installed to /usr/share/icons instead of Themes
- Fixes everywhere

Download Link: https://drive.google.com/open?id=0B6gF35ZZCULwTG54TGlfWm1xVms
UPDATED Instructions: https://github.com/feren-OS/Linux-Mint-to-feren-OS/blob/master/README.md﻿

**Comment by tjw0lf** [comment]
going to try it out now and let you know the output with video again. will be little bit have to install cin again. deleted the vdi partition.

**Comment by tjw0lf** [comment]
UPDATED Instructions please link not working

**Comment by tjw0lf** [comment]
There is an Error Extracting it.
http://i.imgur.com/qDEgF7x.png

**Comment by feren** [comment]
Try downloading it again, I did update it...

**Comment by feren** [comment]
Downloading it now to check if it doesn't work here...

**Comment by feren** [comment]
Yep, you'll need to use `tar -xvzf TARGZ_FILE_HERE` for now...

**Comment by tjw0lf** [comment]
OK trying it Now. Also after we do sudo bash "./Convert to feren OS.sh" and then restart" Do we run the User default script for feren or run it before we restart. Might want to put that in so its as specific as possible. :)

**Comment by tjw0lf** [comment]
https://www.youtube.com/watch?v=y2ElJV6CZVU

don't think the user script working. Also isn't the panel supposed to change if i put on feren theme like in the feren OS or is that just in the feren OS

**Comment by feren** [comment]
@tjw0lf You're supposed to run 'User Defaults.sh' for the panel (To your question, no, that's Theme**r**'s job (is Themer there BTW?))

**Comment by feren** [comment]
@tjw0lf Hmm, hang on, watched the video, will try to fix the boot screen and Themer launcher... (Installing Mint for testing to a VM...)

**Comment by tjw0lf** [comment]
OK What boot screen are you referring too. Do you mean the Mint logo. Also Is the panel supposed to change also with feren theme. like how its in feren OS.

**Comment by feren** [comment]
@tjw0lf 1. Like I said before, no, Themer / User Defaults.sh are meant to control the panel settings, Themes is merely just theming mix n' match
2. In feren OS, the boot screen is black with a while feren OS logo while it's booting, for some reason or another, it's working at shutdown on your VM, but not on boot... (Text Plymouth = Plymouth Error Loading Theme)

**Comment by tjw0lf** [comment]
@feren This is the first you said that never told me before. I didn't know :)  so the user Defaults.sh is for the panel. That's not working yet in Mint right. I was just wondering if the panel supposed to be the same as like in feren OS.or it doesn't change at all in the Mint script. If its supposed to change what tool do we use in Mint. If the the panel doesn't change with mint script like OS feren then thats cool.

**Comment by feren** [comment]
@tjw0lf In the Mint script, it doesn't change it at all, the User Defaults script does that job post-conversion...

**Comment by tjw0lf** [comment]
your still fixing the User Defaults script right... And the rest that didn't work also

**Comment by feren** [comment]
Yeah, I've got a LM 18 VM dandy with snapshots for easy testing... (VMWare)

**Comment by tjw0lf** [comment]
Is this the latest of feren OS https://mega.nz/#!FggXjZaA!qQUYRrmU7UQ2du_aG8xRi8emFdfKoxt4t8-lY9_aXxA

**Comment by feren** [comment]
@tjw0lf Yeah

**Comment by tjw0lf** [comment]
How can i change the folder color on the panel thats brown. Whats the name? where its at. I have the other colors in folder in filesystem change but not sure what the name is for the one on the panel that ones not changing

**Comment by feren** [comment]
@tjw0lf Thanks!

**Comment by feren** [comment]
@tjw0lf The Stable version is now ready, just cleaning it up and making it slightly smaller in size and will then test it followed by packaging it, then final release! :D

**Comment by tjw0lf** [comment]
Awesome can't wait

On Nov 17, 2016 3:39 PM, "feren CEO" <notifications@github.com> wrote:

@tjw0lf <https://github.com/tjw0lf> The Stable version is now ready, just
cleaning it up and making it slightly smaller in size and will then test it
followed by packaging it, then final release! :D

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/feren-OS/Linux-Mint-to-feren-OS/issues/1#issuecomment-261362790>,
or mute the thread

**Comment by tjw0lf** [comment]
hello hows it coming along. Did you unsubscribe me? getting werid messeges saying not subscribed

**Comment by feren** [comment]
No, didn't unsubscribe anyone

**Comment by feren** [comment]
@tjw0lf Getting on good, tests in progress

**Comment by feren** [comment]
@tjw0lf IT'S HERE!

**Comment by tjw0lf** [comment]
Awesome the link in github page? Right. going to try it out now

**Comment by feren** [comment]
Ok, shall this issue be closed now? ;)

**Comment by feren** [comment]
@tjw0lf Also, when I tested Stable, it worked through the GUI extractor just fine now

**Comment by feren** [comment]
@tjw0lf Your livestream is NOT working... Can't hear you and the video thinks it has an end-point while there's a chat window...

Could you see if you can stream with OBS like sudo does?

**Comment by tjw0lf** [comment]
Ya i know still figuring it all out. First time. I'll see if i can

On Nov 19, 2016 3:15 PM, "feren CEO" <notifications@github.com> wrote:

@tjw0lf <https://github.com/tjw0lf> Your livestream is NOT working... Can't
hear you and the video thinks it has an end-point while there's a chat
window...

Could you see if you can stream with OBS like sudo does?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/feren-OS/Linux-Mint-to-feren-OS/issues/1#issuecomment-261736739>,
or mute the thread

**Comment by feren** [comment]
Oh god, I don't know how to say this, but, my mum told me in a call that my dad has died... Seriously! :'(
...She told me at 23:2X that he's died... D:

**Comment by tjw0lf** [comment]
OH my I'm sorry to hear that sorry for your lose feren :( I hope you the best and get through it my pryers are with you and your family :(

**Comment by feren** [comment]
Odd, the script is apparently causing the same mouse bug... :/

**Comment by tjw0lf** [comment]
For '  who

**Comment by feren** [comment]
Another guy that tried it out got the bug on their LM

**Comment by tjw0lf** [comment]
Please ask them what mouse they are using. Brand model.

**Comment by feren** [comment]
Odd, the bluetooth mouse I have works just fine...

**Comment by tjw0lf** [comment]
What model mouse was it and brand?..... Mine works fine also no problems. I want to be your full tester if i can be I can do a video showing it works on my pc and laptop. The ask them to list there specs and Mouse name and model. Then i can go and buy it and buy another one that's different and test them both.

**Comment by feren** [comment]
Microsoft Bluetooth Mouse (came with the laptop) over here... BTW, can you test it on a real machine?

**Comment by tjw0lf** [comment]
Was that the other guys mouse said having problems. yep going to test on real hardware with my machine and laptop. It will just be little while until i get my money. Next month.
