### ISSUE TITLE
Operation Peripheral Fixer: PHASE 2

### ISSUE THREAD

**Issue by TechRage** [feren-OS/Linux-Mint-to-feren-OS#3]
I tried the conversion tool on a new partition of Linux Mint 18.1, towards the end of the installation, I started to encounter the mouse bug again.  It takes one click on the mouse to wake it up then I can start using it. Before executing the script, I was not experiencing this issue with Linux Mint 18.1 Cinnamon.

This is a wired mouse connected to my computer. I purchased a wireless mouse and this doesn't happen with it.

**Comment by feren** [comment]
@TechRage Ok, phase 1 is complete, here's Phase 2:
Reinstall Mint, then open the script IN THE TEXT EDITOR, then copy the first command, paste it in Terminal, and run it as Sudo while CD'd in the LM > fOS folder, and then restart, followed by the same thing for the second command, third command, etc.
Once you get the bug, paste the command you run to cause it on here
